
default: &default
  username: root
  adapter: mysql2
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: recordstore_dev

test:
  <<: *default
  database: recordstore_test

production:
  <<: *default
  database: recordstor_prod
